### ISSUE TITLE
ModuleNotFoundError: No module named 'core'

### ISSUE THREAD

**Issue by alban2020** [Pure-L0G1C/YouTubeViews#44]
Traceback (most recent call last):
  File "C:/Users/alban/PycharmProjects/youtubeviews/youtube.py", line 9, in <module>
    from core.browser import Browser
ModuleNotFoundError: No module named 'core'

Can you help me with this ,i have install core in cmd but that cmd dont find anythink that satisfied the requirement core also i have download ASP.NET Core 3.1 Runtime (v3.1.2) - Windows x64 Installer but still none of them its working . Can you help me ?

**Comment by alban2020** [comment]
After few ways i repair it but i have also this problem 

error: the following arguments are required: visits, urllist, min, max

**Comment by therealpj** [comment]
try:
``` pip3 install core ```
