### ISSUE TITLE
 youtube_views.py: error: the following arguments are required: visits, urllist, min, max

### ISSUE THREAD

**Issue by alban2020** [Pure-L0G1C/YouTubeViews#48]
usage: youtube_views.py [-h] visits urllist min max
youtube_views.py: error: the following arguments are required: visits, urllist, min, max

When I run the program this is what it show ,i have try few things to fix it but i havent do it .
Can you help me to fix ?

**Comment by Chan255** [comment]
you have to download those requirments

**Comment by alban2020** [comment]
I had download all those requirments but dosesnt work : 
certifi==2019.9.11
chardet==3.0.4
html5lib==1.0.1
idna==2.8
mechanize==0.4.3
PySocks==1.7.1
requests==2.22.0
six==1.12.0
urllib3==1.25.6
webencodings==0.5.1

If is any of them that i have requirments tell me .
btw thanks for yout helping

**Comment by Chan255** [comment]
I honestly don’t really get this, I don’t know where to put the code or
where to run the stuff :/ if you could help me that would be great too lol

**Comment by alban2020** [comment]
I dont know which contry you live but here in my contry is 3 a.m .I need a little sleep becouse I have lession tomrrow on my university class zoom .Btw I fix the problem that i had but you know  now i have problem with tor .I had download it but its say again download the tor when it run .I see it in different browser and it seem that i must run on ubuntu .

I will help you after few hours ,becouse i need some sleep .Also which os are your using on pc ?

**Comment by Chan255** [comment]
Okay yeah that’s fine get some sleep, but I’m on Windows 10

**Comment by alban2020** [comment]
hello bro ,I have been busy all the day also i have trying this program .I fixed all the problem and its actually runing ,i dont know if it work in views becouse i see a lot in issue problem that dont work .Btw i hope i will work .So how can i help you ?

**Comment by Chan255** [comment]
I have no clue how to run it or how to use it

**Comment by alban2020** [comment]
First you must try to install kali linux (i have install on my base system )but you can install it in virtualbox.Watch videon on youtube about this how to install virtualbox and kali linux on it and write me here .To tell you nexy step.

**Comment by Chan255** [comment]
Oof I downloaded Kali Linux on a virtual box but it didn’t come with a
browser lol

**Comment by Chan255** [comment]
Okay I got Kali Linux on a VM now what

**Comment by alban2020** [comment]
I find the perfect video on youtube just for you : 
[https://www.youtube.com/watch?v=ec_XL7Lu-dQ&t](url)
watch him and he will how to use the program.

**Comment by Chan255** [comment]
Somethings wrong with the YouTube link?

**Comment by alban2020** [comment]
https://www.youtube.com/watch?v=ec_XL7Lu-dQ&t 
copy and paste in other tab browser

**Comment by Chan255** [comment]
Yeah it just brung me to “https://url

**Comment by Chan255** [comment]
Ok there we go it’s working now

**Comment by alban2020** [comment]
Does it work becouse on my youtube channel the views arent working.

**Comment by Chan255** [comment]
I have not tested it yet. But that guy has a lot of great videos. Thanks
for showing me him! I’ll let you know if I figure it out, thanks again

**Comment by alban2020** [comment]
nahh for me its not working ,i will open a new issue so that admin can solve it (it need new proxy )

**Comment by alban2020** [comment]
Hey bro did the program work ?
